version: '3'
services:
  #  astro:
  #    build:
  #      context: .
  #      dockerfile: ./.docker/astro/Dockerfile
  #    restart: unless-stopped
  #    container_name: astro
  #    ports:
  #      - 3000:3000
  #    networks:
  #      - directus
  #    command: pnpm run dev --host

  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./extensions:/directus/extensions
      - ./uploads:/directus/uploads
    networks:
      - directus
    environment:
      POSTGRES_USER: 'fox'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'signarius'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./.env:/directus/.env:ro
      - ./config:/directus/config
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'


      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

  pgbackups:
    container_name: Backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./dump:/backups
    links:
      - database
    depends_on:
      - database
    #    command:
    #      - sh -c "./backup.sh"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=signarius
      - POSTGRES_USER=fox
      - POSTGRES_PASSWORD=123
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81
    networks:
      - directus

volumes:
  pgadmin-data:

networks:
  directus: